global:
  ingressSubdomain: <dev-cluster-name>.us-south.containers.appdomain.cloud
  tlsSecretName: au-icr-io

<app-chart-name>:
  replicaCount: 3
  
  ingress:
    enabled: true
    tlsSecretName: au-icr-io

